quotes = [
    "“Balance must be maintained, and yet destinies remain variable. Death has its own rules, yet it is still hard to predict. Remember – no matter where, no matter when, no matter what the reason – one should never poke fun at death.” – Hu Tao",
    "“Every journey has its final day. Don’t rush!” – Zhongli",
    "“I never embark on a journey without a good book to accompany me.” – Xingqiu",
    "“When you don’t know what to do, just take the first step. The rest will figure itself out naturally.” – Beidou",
    "“If you can change something, change it. If you can’t, don’t waste time thinking about it.” – Beidou",
    "“Reality is the stillness buried deep beneath the illusion.” – Raiden Shogun",
    "“You should know that all power comes at a price. For every bit of power you gain, so too do you gain more responsibility.” – Zhongli",
    "“I can’t believe that some people actually drink grape juice… if they had a little more patience, they would find that it ferments into the most exquisite wine.” – Kaeya",
    "“Some ambitions have the power to heal wounds, to bring victory, to inspire hope. But some ambitions outlive their masters long after their soul ascends. They remain as they were in the beginning, burning bright and true, for all eternity.” – Yae Miko",
    "“The world would lose much of its appeal if wholly stripped of delusion and falsehood.” – Fischl",
    "“Only once you know and respect death can you truly understand the value of life.” – Hu Tao",
    "“There are only two kinds of things – those that must be done and those that must not.” – Raiden Shogun",
    "“My greatest wish? It has always been to roam free and experience the whole world. Now I would add that wherever I go, it simply must be with you! Each day with you is an adventure, and where adventurers go, storytellers must follow!” – Venti",
    "“Only once you know and respect death, can you truly understand the value of life” – Hu Tao",
    "“If you make a promise, you keep it, if you make a mistake, you apologize. And if you give someone a dream, you defend it to the end.” – Childe",
    "“Yesterday’s experiences make me stronger today.” – Keqing",
    "“Respect must be given to the will of every creature. Each fish in the ocean swims in its own direction” – Sangonomiya Kokomi",
    "“With authority over a thousand comes responsibility to a thousand.” – Ganyu",
    "“Do not seek to emulate the past, for there is no law that can suffice for all time.” – Yanfei",
    "“There’s no style in resorting to violence, it’s simply the worst of all the bad decisions you could make” – Ningguang",
    "“If you lie on the grass, you can feel the heartbeat of the world” – Ganyu",
    "“As the wind continues to blow, so too shall I continue to fight” – Jean",
    "“I’ll remind you again: The law can be both a help and a hindrance.” – Yanfei",
    "“What does freedom really mean, when demanded of you by a god?” – Dainsleif",
    "“When your heart is set on something, you get closer to your goal with each passing day.” – Keqing",
    "“Visions are a light in the sea of darkness that surrounds those who have lost their way. But for those who have faith, they are little more than badges of conviction.” – Diluc",
    "“In a trade war, the perfect hunter leaves no trace.” – Ningguang",
    "“I’m flying with you in my heart.” – Aether / Lumine",
    "“Discipline is everything. Unbridled passion can have disastrous consequences. Trust me, I would know.” – Chongyun",
    "“Trade relies on both contracts and fairness. There is one thing you must never forget when making and abiding by a contract: if fairness is lost, then the contract shall become proof of one’s deception.” – Zhongli",
    "“”When the last sparks of the fireworks have disappeared into the sky, they turn into rain and snow, and will fall upon the earth again, nourishing the land and nurturing humanity, so that someday they can be sent up into the sky again and display their magnificence.” Of the many stories my father told me, this one is my favorite.” – Yoimiya",
    "“Do not trust your eyes! Your eyes can lie to you.” – Ningguang",
    "“It falls to me to place the truth before your eyes, in all its ugliness.” – Yae Miko",
    "“The world remains constant over the centuries. But human life is like the dew at dawn or a bubble rising through water. Transitory.” – Raiden Shogun",
    "“I gotta find something fun to do… sitting around doing nothing is a fate worse than death.” – Hu Tao",
    "“A successful day starts from the morning. Let’s give it our all today.” – Jean",
    "“With you by my side, though our mouths stay silent, my heart is at peace.” – Raiden Shogun",
    "“A cold beer after a hard day’s work… nothing like it!” – Beidou",
    "“Going out into the world and investigating, turning the “unknown” into the “known.”” – Albedo",
    "“The fate that brings people together is not a cord so easily cut.” – Kazuha",
    "“Let's embark on a journey, for I am the breeze. We will meet again, no matter how far along the road. Life has just begun, and maybe the whole world can be my home.” – Kazuha",
    "“I often travel during storms, which means my eyes are often blinded by the rain. Many times, I couldn't even see what was right in front of me.” – Kazuha",
    "“Come driving rain or winds that churn, I shall return, by blade alone, armed, if barefoot, to my home.” – Kazuha",
    "“I love it when it snows. The world falls completely silent... and I can sleep undisturbed.” – Kazuha",
    "“So long as I have my blade by my side, there is nowhere I cannot go.” – Kazuha",
    "“Clear weather all around brightens the heart.” – Kazuha",
    "“As one travels the world, sorrows and frustrations are bound to journey with you.” – Kazuha",
    "“Perhaps you should get some rest? A weary mind is a recipe for flavorless food.” – Kazuha",
    "“I never stay in a single place for very long. Stagnancy dulls both my connection with nature and the blade I wield. While I am still able to, I want to travel far and wide and meet all sorts of different people.” – Kazuha",
    "“Wherever in this world I roam, I carry memories of my home. This blade... it is the last link I have to the land of my birth.” – Kazuha",
    "“Farewell, dear gulls, please calm your cries. From this day forth, I am a wanderer once more.” – Kazuha",
    "“Compared to the storms I've encountered out at sea, this is really quite tame.” – Kazuha",
    "“Eternity stretches things out over a long time. But each moment within it becomes all the more fragile.” – Scaramouche",
    "“My chest will never again be defiled by worldly filth. I will scrub away every last trace of human emotion.” – Scaramouche",
    "“It took three betrayals for me to finally understand: The world is just an elaborate tapestry of lies. My fury will never be quelled. \nThe first to betray me was a god. My creator... my mother. Valuing strength above all, she saw no worth in me, and I was discarded. \nThe second was a human. My family... my friend. Consumed by fear, he saw me as an abomination. \nThe third was one exactly like me. A hope for the future... a fledgling barely out of the nest. Powerless before his mortality, he broke his promise to me. \nHumans... they can't be trusted. And the gods fill me with pure loathing. So I said good riddance! I denounce the world and laugh in its face.” – Scaramouche",
    "“Just like a bubble on the water. Beautiful for a moment, then total destruction.” – Scaramouche",
    "“From the outside, Inazuma looks pretty impenetrable, but on the inside, it's a land of opportunity. With a little effort, we were able to break them down from within.” – Scaramouche",
    "“Inactivity serves no purpose whatsoever.” – Raiden Shogun",
    "“An “ambition” is a yearning for something material, or a concrete outcome. It is finite in nature, and will be replaced by a new ambition in due course.” – Raiden Shogun",
    "“Do you wish to know the truth about the shooting stars at night? They are but fleeting moments of luminosity.” – Raiden Shogun",
    "“All the world holds dear is but a backdrop of constant motion. I stand before it alone and unchanging.” – Raiden Shogun",
    "“People flee out of a desire to live on. And the desire to live on stems from a feeling of having unfinished business in life.” – Raiden Shogun",
    "“Rainfall alone does not constitute a storm. Thunder is required.” – Raiden Shogun",
    "“Don't try and get me to cook. I can take care of anything else, but not that.” – Raiden Shogun",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    "“” – ",
    
]