quotes = [
    "“Balance must be maintained, and yet destinies remain variable. Death has its own rules, yet it is still hard to predict. Remember – no matter where, no matter when, no matter what the reason – one should never poke fun at death.” – Hu Tao",
    "“Every journey has its final day. Don’t rush!” – Zhongli",
    "“I never embark on a journey without a good book to accompany me.” – Xingqiu",
    "“When you don’t know what to do, just take the first step. The rest will figure itself out naturally.” – Beidou",
    "“If you can change something, change it. If you can’t, don’t waste time thinking about it.” – Beidou",
    "“Reality is the stillness buried deep beneath the illusion.” – Raiden Shogun",
    "“You should know that all power comes at a price. For every bit of power you gain, so too do you gain more responsibility.” – Zhongli",
    "“I can’t believe that some people actually drink grape juice… if they had a little more patience, they would find that it ferments into the most exquisite wine.” – Kaeya",
    "“Some ambitions have the power to heal wounds, to bring victory, to inspire hope. But some ambitions outlive their masters long after their soul ascends. They remain as they were in the beginning, burning bright and true, for all eternity.” – Yae Miko",
    "“The world would lose much of its appeal if wholly stripped of delusion and falsehood.” – Fischl",
    "“Only once you know and respect death can you truly understand the value of life.” – Hu Tao",
    "“There are only two kinds of things – those that must be done and those that must not.” – Raiden Shogun",
    "“My greatest wish? It has always been to roam free and experience the whole world. Now I would add that wherever I go, it simply must be with you! Each day with you is an adventure, and where adventurers go, storytellers must follow!” – Venti",
    "“Only once you know and respect death, can you truly understand the value of life” – Hu Tao",
    "“If you make a promise, you keep it, if you make a mistake, you apologize. And if you give someone a dream, you defend it to the end.” – Childe",
    "“Yesterday’s experiences make me stronger today.” – Keqing",
    "“Respect must be given to the will of every creature. Each fish in the ocean swims in its own direction” – Sangonomiya Kokomi",
    "“With authority over a thousand comes responsibility to a thousand.” – Ganyu",
    "“Do not seek to emulate the past, for there is no law that can suffice for all time.” – Yanfei",
    "“There’s no style in resorting to violence, it’s simply the worst of all the bad decisions you could make” – Ningguang",
    "“If you lie on the grass, you can feel the heartbeat of the world” – Ganyu",
    "“As the wind continues to blow, so too shall I continue to fight” – Jean",
    "“I’ll remind you again: The law can be both a help and a hindrance.” – Yanfei",
    "“What does freedom really mean, when demanded of you by a god?” – Dainsleif",
    "“When your heart is set on something, you get closer to your goal with each passing day.” – Keqing",
    "“Visions are a light in the sea of darkness that surrounds those who have lost their way. But for those who have faith, they are little more than badges of conviction.” – Diluc",
    "“In a trade war, the perfect hunter leaves no trace.” – Ningguang",
    "“I’m flying with you in my heart.” – Aether / Lumine",
    "“Discipline is everything. Unbridled passion can have disastrous consequences. Trust me, I would know.” – Chongyun",
    "“Trade relies on both contracts and fairness. There is one thing you must never forget when making and abiding by a contract: if fairness is lost, then the contract shall become proof of one’s deception.” – Zhongli",
    "“”When the last sparks of the fireworks have disappeared into the sky, they turn into rain and snow, and will fall upon the earth again, nourishing the land and nurturing humanity, so that someday they can be sent up into the sky again and display their magnificence.” Of the many stories my father told me, this one is my favorite.” – Yoimiya",
    "“Do not trust your eyes! Your eyes can lie to you.” – Ningguang",
    "“It falls to me to place the truth before your eyes, in all its ugliness.” – Yae Miko",
    "“The world remains constant over the centuries. But human life is like the dew at dawn or a bubble rising through water. Transitory.” – Raiden Shogun",
    "“I gotta find something fun to do… sitting around doing nothing is a fate worse than death.” – Hu Tao",
    "“A successful day starts from the morning. Let’s give it our all today.” – Jean",
    "“With you by my side, though our mouths stay silent, my heart is at peace.” – Raiden Shogun",
    "“A cold beer after a hard day’s work… nothing like it!” – Beidou",
    "“Going out into the world and investigating, turning the “unknown” into the “known.”” – Albedo",
    "“The fate that brings people together is not a cord so easily cut.” – Kazuha",
    "“Let's embark on a journey, for I am the breeze. We will meet again, no matter how far along the road. Life has just begun, and maybe the whole world can be my home.” – Kazuha",
    "“I often travel during storms, which means my eyes are often blinded by the rain. Many times, I couldn't even see what was right in front of me.” – Kazuha",
    "“Come driving rain or winds that churn, I shall return, by blade alone, armed, if barefoot, to my home.” – Kazuha",
    "“I love it when it snows. The world falls completely silent... and I can sleep undisturbed.” – Kazuha",
    "“So long as I have my blade by my side, there is nowhere I cannot go.” – Kazuha",
    "“Clear weather all around brightens the heart.” – Kazuha",
    "“As one travels the world, sorrows and frustrations are bound to journey with you.” – Kazuha",
    "“Perhaps you should get some rest? A weary mind is a recipe for flavorless food.” – Kazuha",
    "“I never stay in a single place for very long. Stagnancy dulls both my connection with nature and the blade I wield. While I am still able to, I want to travel far and wide and meet all sorts of different people.” – Kazuha",
    "“Wherever in this world I roam, I carry memories of my home. This blade... it is the last link I have to the land of my birth.” – Kazuha",
    "“Farewell, dear gulls, please calm your cries. From this day forth, I am a wanderer once more.” – Kazuha",
    "“Compared to the storms I've encountered out at sea, this is really quite tame.” – Kazuha",
    "“Eternity stretches things out over a long time. But each moment within it becomes all the more fragile.” – Scaramouche",
    "“My chest will never again be defiled by worldly filth. I will scrub away every last trace of human emotion.” – Scaramouche",
    "“It took three betrayals for me to finally understand: The world is just an elaborate tapestry of lies. My fury will never be quelled. \nThe first to betray me was a god. My creator... my mother. Valuing strength above all, she saw no worth in me, and I was discarded. \nThe second was a human. My family... my friend. Consumed by fear, he saw me as an abomination. \nThe third was one exactly like me. A hope for the future... a fledgling barely out of the nest. Powerless before his mortality, he broke his promise to me. \nHumans... they can't be trusted. And the gods fill me with pure loathing. So I said good riddance! I denounce the world and laugh in its face.” – Scaramouche",
    "“Just like a bubble on the water. Beautiful for a moment, then total destruction.” – Scaramouche",
    "“From the outside, Inazuma looks pretty impenetrable, but on the inside, it's a land of opportunity. With a little effort, we were able to break them down from within.” – Scaramouche",
    "“Inactivity serves no purpose whatsoever.” – Raiden Shogun",
    "“An “ambition” is a yearning for something material, or a concrete outcome. It is finite in nature, and will be replaced by a new ambition in due course.” – Raiden Shogun",
    "“Do you wish to know the truth about the shooting stars at night? They are but fleeting moments of luminosity.” – Raiden Shogun",
    "“All the world holds dear is but a backdrop of constant motion. I stand before it alone and unchanging.” – Raiden Shogun",
    "“People flee out of a desire to live on. And the desire to live on stems from a feeling of having unfinished business in life.” – Raiden Shogun",
    "“Rainfall alone does not constitute a storm. Thunder is required.” – Raiden Shogun",
    "“Don't try and get me to cook. I can take care of anything else, but not that.” – Raiden Shogun",
    "“Some ambitions have the power to heal wounds, to bring victory, to inspire hope. But some ambitions, outlive their masters, long after their soul ascends. They remain as they were in the beginning, burning bright and true, for all eternity.” – Yae Miko",
    "“I need your actions, not your words.” – Yae Miko",
    "“If you find yourself at your wit's end, take it out and see what happens. Maybe your prayers will be answered, and all your problems will disappear in the blink of an eye.” – ",
    "“Humans are just fascinating creatures, that's why I'm so fond of them. They live such short lives, but for the time they're around, they shine as bright as the midday sun.” – ",
    "“What your people need from you is not your promises. They want your attention... your divine gaze.” – Yae Miko",
    "“I must say, this is quite the cunning trap. But have I walked into your trap? Or have you... walked into mine?” – Yae Miko",
    "“So are we to just abandon the notion of progress.... for the sake of wishful thinking?” – Yae Miko",
    "“There are nations where humans cast their god aside and stride forward...?” – Yae Miko",
    "“Ei never said goodbye to me before she stepped into the Plane of Euthymia. Perhaps it's just my wishful thinking, but I think she did this deliberately, as her way of keeping our friendship eternal. By neither saying goodbye nor seeing me again, our relationship will remain forever how it was.” – Yae Miko",
    "“You will miss much by refusing progress. You seek to prevent loss, but have you considered all you are losing by remaining here in stasis for all eternity?” – Yae Miko",
    "“Well? The things you wanted to see, but also wished not to see, are here before you.” – Yae Miko",
    "“Eternity is far too cruel a fate for you, Ei. Not only have you stopped paying attention to the world, but you have stopped paying attention to yourself.” – Yae Miko",
    "“I'm not the kind of person who risks life and limb for any old reason.” – Yae Miko",
    "“You're slurring a little. Wait a moment, I'll brew a pot of sobering tea. It'll be ready in only six hours.” – Zhongli",
    "“Osmanthus wine tastes the same as I remember... but where are those who share the memory?” – Zhongli",
    "“For those that live too long, the friends of days gone by and scenes from their adventures live on in their memories. As such I have no regrets in meeting you, friend. Should the day ever come that we are not together, you will continue to shine like gold in my memories.” – Zhongli",
    "“Dreams are rich bundles of human wisdom.” – Nahida",
    "“Life inherently has many rules and restrictions, each with its own significance and reason to exist. They can't be broken on a whim.” – Nahida",
    "“Everything in this world runs in a loop. As for the truth... that's on you to find out. So no matter how strange or spooky things might look on the surface, maybe all they point to in the end is a small and simple secret. In the end, I'm just the Moon. The real Sun is long gone.” – Nahida",
    "“Your dreams are like the pure and delicate bubbles floating on the water. The more beautiful the illusion, the more it fascinates me.” – Nahida",
    "“There is no need to wonder about my name. Maybe one day in the future, we will meet in another place.” – Nahida",
    "“Sorry... Paimon's mouth just works so much faster than everyone else's.” – Paimon",
    "“Two hundred of Paimon would squish you flat, you know!” – Paimon",
    "“Liar liar pants on fire!” – Paimon",
    "“If you're suggesting that we escalate this from a verbal exchange to a physical one, I accept.” – Alhaitham",
    "“I don't need to fight I only need to think. Everything is connected. All I have to do is find the weakest link, deal with the causal factors and everything else tends to resolve itself. Essentially, more time on contemplation, less time on execution.” – Alhaitham",
    "“All intellectuals are lunatics in the eyes of fools. I'll take that as a compliment.” – Alhaitham",
    "“Those who understand the rules can delineate boundaries, and identify gray areas.” – Alhaitham",
    "“To achieve this impossible task, it sounds like you'll need to fool your own heart first. Although it may feel like a trick, self-encouragement may be the most important tool we have.” – Alhaitham",
    "“Naturally, I slept just fine. After all, a good rest should be considered part of the plan, since energy is an important resource.” – Alhaitham",
    "“There is always an opportunity for safety after danger passes.” – Alhaitham",
    "“The Eremites once said that I was a lunatic. Perhaps a little madness is essential to be successful in research.” – Alhaitham",
    "“If you want to raise a vicious wolf, you need to make sure that you can avoid its bite.” – Alhaitham",
    "“The point of discussion is to arrive at a solution. Let's cut the small talk and move to the next point.” – Alhaitham",
    "“When you are unable to understand a reasearcher's actions, most cases can be attributed to curiosity.” – Alhaitham",
    "“Have I ever failed to follow through on my word in the past?” – Alhaitham",
    "“It's crucial to dissipate any tension before we execute our plan.” – Alhaitham",
    "“After all, there will always be those in this world who are dissatisfied with life as designed for them by the Akasha, and wish to change their fate.” – Alhaitham",
    "“Observation is the first step of any experiment, but observing the current world doesn't satisfy me. It lacks an important dimension - that of time.” – Il Dottore",
    "“Even the God of Wisdom is restricted by the habits of cognition. How disappointing.” – Il Dottore",
    "“Oh, no. I certainly have my own convictions. They just don't fit your standards, that's all.” – Il Dottore",
    "“The world is full of lost ballads just waiting to be rediscovered.” – Venti",
    "“Let us make music, not war, and resolve our conflicts through song.” – Venti",
    "“May the winds bless your travels!” – Venti",
    "“Many mortals fear lightning... incomprehensible. Fear of something so common.” – Xiao",
    "“Reduced to just standing around. How absurd.” – Xiao",
    "“Once the snow is thick enough, we can eat it.” – Xiao",
    "“If you awake to a knife at your throat, if monsters dig their claws into you, if death comes knocking at your door, call out my name. Adeptus Xiao. I will be here when you call.” – Xiao",
    "“A warrior must always be ready to face any challenge with his blade. The outcome of the battle is irrelevant - what matters is that you learn from the experience.” – Childe",
    "“Comrade. Make sure you keep training too. Otherwise, who will be left to fight me to the death when the world lies defeated at my feet?” – Tartaglia",
    "“A warrior's strength is like a dome. The bigger the dome, the more opponents he can challenge inside it.” – Childe",
    "“Where I'm from, if we didn't keep moving, we'd freeze to death. Literally.” – Childe",
    "“The rules of war are woven in the womb: the victors shall burn bright, while the losers must turn to ash.” – Dainsleif",
    "“The God of Contracts, senselessly slaughtered as his people watched on in horror. In the end, he will sign the contract to end all contracts.” – Dainsleif",
    "“Now, you who has set foot in this world. \nYour journey has reached its end, but one final doorway remains. \nStep forth, if you have understood the meaning of your journey. \nDefeat me, command me to step aside, show me that you are worthier than I to rescue her. \nThen, the threads of all fate will be yours to re-weave. \nMy memory has all but faded completely... but I will always remember how much she too, loved these flowers.” – Dainsleif",
    "“Sometimes, hopes and dreams bring suffering instead of happiness.” – Kaveh",
    "“The ability to appreciate beauty is an important virtue.” – Kaveh",
    "“If you ask me, I think the people spreading rumors around here don't have access to any real information.” – Kaveh",
    "“I don't understand why people insist on going all out to try and prove how their existence is more valuable than everyone else's. To exist in the first place is a beautiful thing, and that's enough... isn't it?” – Ganyu",
    "“Respect must be given to the will of every creature. Each fish in the ocean swims in its own direction.” – Kokomi",
    "“When small fish gather together, they can act as one body for the protection of all. This is how the weak mount their resistance.” – Kokomi",
    "“Fate had other ideas in store... you can't defy that which flows in your veins.” – Kokomi",
    "“It's said that the depths of a person's heart run deep indeed.” – Kokomi",
    "“Night already? Time seems to slip away when I'm with you.” – ",
    "“To survive hardship, you must prepare for hardship.” – Kokomi",
    "“It takes a broad outlook to become a qualified leader.” – Kokomi",
    "“Brute force is not my modus operandi. But becoming stronger isn't a bad thing.” – Kokomi",
    "“Fireworks are for now, but friends are forever.” – Yoimiya",
    "“It actually doesn't matter what I do. What matters are the people I work with. When I'm with you, even simple things like watching the scenery or kicking a small jar about make me happy.” – Yoimiya",
    "“The unstoppable power of an immovable glacier dwells within me.” – Eula",
    "“Listen, as long as you stick to your own path, it doesn't matter what mother nature throws at you.” – Diluc",
    "“I used to believe... if I was to stamp out evil, I would have to walk alone in darkness. However, seeing your perseverance, I know I was wrong. Friend... I owe you my thanks.” – Diluc",
    "“What lies in wait for us? I rarely stop to think about it. No matter what dares to stand in my way, I must press forward.” – Diluc",
    "“Power is necessary if we are to meet our objectives.” – Diluc",
    "“Visions are a light in the sea of darkness that surrounds those who have lost their way. But for those who have faith, they are little more than badges of conviction.” – Diluc",
    "“Let us carry on, partner. The road ahead is still long.” – Kaeya",
    "“The past cannot be changed, and the future cannot be foretold. As a result, I make sure to always cherish the here and now.” – Cyno",
    "“Good deeds and bad... in the end, all will be placed upon the scales.” – Cyno",
    "“Luck can swing the results of a single game, but it's bound to run out sooner or later.” – Cyno",
    "“What a pity, I majored in botany, and helping people grow a brain is not my area of expertise.” – Tighnari",
    "“The value of knowledge can't simply be quantified in monetary terms.” – Tighnari",
    "“Don't be afraid to make mistakes. It's all part of the learning process.” – Tighnari",
    "“Just as a doctor won't abandon their patients, I will not abandon the forest. You promised me status and reputation. Yet, I do not care for these.” – Tighnari",
    "“Seedlings grow, reaching out with their branches and leaves.” – Tighnari",
    "“Gamblers always place their bets on the next dice roll... but the bankers always have the last laugh, and they never touch a single die.” – Ningguang",
    "“Even if an antique is priceless, the happiness it brings lasts for only the moment you obtain it.” – Ningguang",
    "“A blade is like a tea-leaf. Only those who sample it many times can appreciate its true qualities.” – Ayaka",
    "“Snow that once adorned the world in silver, thaws to reveal the gleam of the fruit upon frost-laden branches.” – Ayaka",
    "“A blade embraces its duty as a jeweler cherishes their gems.” – Ayaka",
    "“Everything comes at a cost. And if you aspire to things that most could never dream of, then naturally, there will be an unimaginable price to pay.” – Ayato",
    "“Power is only a source of comfort when it is concentrated in one's own hands.” – Ayato",
    "“You want to know about me? Hmm. Things aren't always a case of the more you know, the better.” – Ayato",
    "“I'm no stickler for doing things in a certain way. Whatever method you use, the important thing is that it delivers acceptable results.” – Ayato",
    "“If you throw fallen flowers onto the stove, the searing heat infuses them with one final spark of vitality, and for a brief moment, they radiate a more glorious glow than the flames themselves... it was a short life they lived, but it was by no means a wasted one.” – Ayato",
    "“Most people hunker down against a strong headwind. Only a few people know how to utilize it to their advantage.” – Ayato",
    "“Everything's in place, and they've taken the bait - yes. Now to start reeling them in...” – Ayato",
    "“The weather and our moods are the same - they can both get gloomy. It's all right, though, because the sky will become even brighter after the rain.” – Nilou",
    "“In adventuring, as in business, you always have to seize the opportunity while it's there.” – Keqing",
    "“If you feel strongly about something, you should speak up and take action.” – Keqing",
    "“I'm all for work-life balance, but I think this is pushing it.” – Keqing",
    "“Direct and clear observation are imperative to a good experiment. This is just a simple exercise.” – Albedo",
    "“Genius? A number of people call me that. But I don't think I'm any “genius”.” – Albedo",
    "“Fate is called as such, for it cannot be changed, nor can it be reversed. It can only but be accepted.” – Mona",
    "“One need not scry to know today's weather will be good.” – Mona",
    "“Divination is about precisely foretelling one's written destiny. Over-embellishing that fate only leads to misconception.” – Mona",
    "“The work of the astrologer is to show people what fate has in store for them, and that's exactly what I do. There will always be those however, who are unable to accept what they are told.” – Mona",
    "“I'm not lazy, I just know to save my energy for when I need it most.” – Lisa",
    "“Why not keep me company for a while... There'll be plenty of time for work later.” – Lisa",
    "“You have my complete and full support. Of course, if your path ever deviates from justice, I will not hesitate to point it out.” – Jean",
    "“I shoulder the knights' trust and the people's hope. It is for this reason, I must stay vigilant.” – Jean",
    "“Our work will not handle itself... but, I suppose the occasional short break is warranted. Let us rest for a couple of minutes.” – Jean",
    "“Don't be too ready to believe people when they cross their heart and hope to die. Sweet talkers only say what you want to hear. And think twice before meeting someone else's gaze - your eyes speak volumes about what you're thinking.” – Yelan",
    "“Sometimes, you have to strike hard and fast at just the right moment to expose the lies while avoiding any unwanted interference.” – Yelan",
    "“Navigating the world is a whole lot easier with a few different identities to choose from.” – Yelan",
    "“Finding the truth might sound simple, but it takes perseverance to stick to the trail of clues and it takes strength to follow them deep into dangerous territory.” – Yelan",
    "“You have to be very careful with sweets. That powerful sense of satisfaction... it weakens your willpower and makes you relaxed. It only takes a few bites to get addicted, and with long-term consumption, you'll slowly but surely lose your edge.” – Yelan",
    "“Clues are links in a chain. You have to trace them all the way back to where everything began before there can be a resolution.” – Yelan",
    "“Mind be purged, world be saved.” – Shenhe",
    "“Demons are masters of deception, never let down your guard!” – Shenhe",
    "“Just remember not to say too much. Be discreet.” – Dehya",
    "“A photo can never replace an artist's painting because the former has no spirit to it.” – Dehya",
    "“Sometimes when you're out on a limb, you gotta double down to seal the deal, you know?” – Dehya",
    "“Us mercs, we pretty much live from one day to the next.” – Dehya",
    "“I see through it all. And unlike them, I could never be hostile towards anything who's never done anything wrong.” – Dehya",
    "“I'm only doing this because I respect your determination, not because I agree with you.” – Dehya",
    "“Your kindness warms my heart more than the brightest flame ever could.” – Thoma",
    "“My strength is your shield, and I will always be here to protect you.” – Thoma",
    "“Everyone has their own perspective, there's nothing strange about that.” – Thoma",
    "“It feels like... a fire inside of me has just begun to burn.” – Thoma",
    "“Don't run on the ice... 'cause if you fall down, I won't help you up, you gotta learn somehow.” – Thoma",
    "“Y'know... too much alcohol is bad for you, anyway. So not drinking is a good thing.” – Thoma",
    "“Sometimes the law is compatible with human nature, but sometimes the two conflict. Balancing the two is a discipline in its own right.” – Yanfei",
    "“Everything is negotiable, except overtime.” – Rosaria",
    "“Work hard and live each day to the fullest. That is what life in Mondstadt is all about, isn't it?” – Rosaria",
    "“Perhaps a god has the power to protect everyone if they would choose to do so, but that would never happen. Otherwise, people's suffering couldn't ever be taken seriously.” – Rosaria",
    "“If the gods haven't given up on me, I guess that means I shouldn't give up on me either.” – Bennett",
    "“Only dreams can awaken consciousness from the deepest darkness.” – Rukkhadevata",
    "“Just let me know if you ever find yourself in a pinch. I can help you out.” – Kuki Shinobu",
    "“I have a poor memory for most things. But as far as I know, that doesn't matter.” – Qiqi",
    "“May my final stand be a monument to chivalry.” – Xingqiu",
    "“Even though the rain has stopped, you still need to watch out for puddles. Just like how the past stays in the memory long after.” – Collei",
    "“Even if it's a life-or-death situation, I'll never need to rely on their power again.” – Collei",
    "“Sorry, Master says I'm not supposed to eat anything that looks suspicious.” – Collei",
    "“Master is always reminding me that practice makes perfect.” – Collei",
    "“To strike your foe takes unity between mind, arrow, and bow.” – Kujou Sara",
    "“The sound of rain masks the enemy's footsteps.” – Kujou Sara",
    "“The smiles on the faces of the people I've helped keeps me going.” – Barbara",
    "“Everyone is working super hard, we should be too!” – Barbara",
    "“Even when we're not looking up at the stars they're always there, watching over us.” – Layla",
    "“Truth repeats its course.” – Faruzan",
    "“To make a five-star dish, you need ten-star passion!” – Xiangling",
    "“Keep your weapon at the ready! You never know what's around the corner...” – Gorou",
    "“Protecting my soldiers doesn't just mean having a robust defense in place. Sometimes, it means going on the attack!” – Gorou",
    "“The fighting has ceased for now... commence physical training!” – Gorou",
    "“A strong body shows strength and instills confidence in others around you. I must always stay at the top of my game!” – Gorou",
    "“Remember that I don't go easy on anyone, even you!” – Amber",
    "“Achievement in a field is the result of how hard you are willing to work at it, not how much you enjoy it.” – Yun Jin",
    "“As the saying goes, you never truly know someone until you meet them in person, and at long last, I finally have the great honor of meeting you today.” – Yun Jin",
    "“Teeth. Claws. Legs. All bigger. All stronger! To protect you.” – Razor",
    "“Sharpen claws. Sharpen teeth. Become stronger!” – Razor",
    "“You sleep now. I keep watch.” – Razor",
    "“I have iron claws and teeth of thunder. I protect you.” – Razor",
    "“Don't put off until tomorrow what you can do today!” – Yaoyao",
    "“This new strength I now gain in the present is preparing me for trials that lie ahead in the future.” – Candace",
    "“A shield is not enough to protect the most important things. That's why I must also wield a spear.” – Candace",
    "“I will always seek to protect the things that are most important, no matter what it takes... even when it looks futile.” – Candace",
    "“Peace and good health should be enjoyed by all... If I can provide everyone with a life such as this, I will be content.” – Candace",
    "“Whenever you need me, I'll be there.” – Noelle",
    "“Now that's how life should be like! Lose the red tape, and live free!” – Xinyan",
    "“Really, can't a girl sport her own style without being looked at like she's some weird creature outta who-knows-where?” – Xinyan",
    "“If there's fire in your soul, you gotta rock 'n' roll.” – Xinyan",
    "“To you who lived here in the past, I hope you liked this song.” – Xinyan",
    "“Everything I do is in the service of life, not death. That's why I'm here with you.” – Aloy",
    "“Getting better. Getting stronger. Always a good thing.” – Aloy",
    "“I'm not much for talking about myself. The mission is what's important.” – Aloy",
    "“Perhaps if only time stands still, will the lightning's glow never fade.” – The Omnipresent God",
    "“There will always be those who dare to brave the lightning's glow.” – Kazuha no Tomo"
]